---
AWSTemplateFormatVersion: '2010-09-09'
Description: Build Lambada functin that will delete indices that with the following format cwl-2017.08.28 older than number of days specified
Parameters:
  Domain:
    Default: none
    Description: Elasticsearch domain
    Type: String
  DeleteAfter:
    Default: 7    
    Description: Number of days to preserve
    Type: String
  Index:
    Default: cwl
    Description: Index/indices to process comma separated, with all every index will be processed except .kibana
    Type: String
  EsEndpoint:
    Default: none
    Description: Name of Elasticsearch instance
    Type: String
  CodeBucketName:
    Default: none
    Description: S3 Bucket where the Lambda code has been uploaded.
    Type: String
Resources:
  LambdaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      - "arn:aws:iam::aws:policy/service-role/AWSLambdaRole"
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: LambdaLogCreation
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ["logs:*"]
            Resource: "arn:aws:logs:*:*:*"
      - PolicyName: ESPermission
        PolicyDocument: 
          Statement:
          - Effect: Allow
            Action: ["es:*"]
            Resource:
              - 'Fn::Sub': >-
                 arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/${Domain}/*
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        S3Bucket: !Ref CodeBucketName
        S3Key: 'es-cleanup-lambda.zip'
      Description: A trigger that deletes indexes
      Environment:
        Variables:
          es_endpoint: !Ref EsEndpoint
          index: !Ref Index
          delete_after: !Ref DeleteAfter
      FunctionName: es-cleanup-lambda
      Handler: es-cleanup.lambda_handler
      MemorySize: 128
      Role: !GetAtt LambdaServiceRole.Arn
      Runtime: "python2.7"
      Timeout: 60
Outputs:
  myStacksRegion:
    Value:  !Ref AWS::Region
  myAccountId:
    Value: !Ref AWS::AccountId  
